name: Renovate

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log level for Renovate, e.g., `info` (default), `debug`"
        required: false
        type: string
      log_format:
        description: "Log format for Renovate, e.g., `pretty` (default), `json`"
        required: false
        type: string

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        env:
          RENOVATE_REPOSITORIES: klippx/graphiql-plugin-apollo-query-plan
          LOG_LEVEL: ${{ inputs.log_level }}
          LOG_FORMAT: ${{ inputs.log_format }}
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_PAT }}
